services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet"]
  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/table-test
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
    command: npm run dev
    depends_on:
      - mongo
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - '4200:80'
    depends_on:
      - backend

volumes:
  mongo-data: