services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/table-test
    volumes:
      - ./backend:/app
    command: npm run dev

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet"]

volumes:
  mongo-data: